#!/bin/sh /etc/rc.common

USE_PROCD=1
START=94
STOP=10

CONF=/etc/xray-frag/config.json

start_service() {
	[ -f "$CONF" ] || return 1
	procd_open_instance
	procd_set_param command /usr/bin/xray run -c "$CONF"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "xray-frag"
}
